from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

ZH_MAIN = ROOT / "src/locale/zh-Hans.ts"
EN_MAIN = ROOT / "src/locale/en-US.ts"
ZH_DIR = ROOT / "src/locale/zh-Hans"
EN_DIR = ROOT / "src/locale/en-US"

COMMON_KEYS = [
    "common",
    "pages",
    "api",
    "storage",
    "feed",
    "editor",
    "account_picker",
    "home",
    "me",
]

COMMUNICATION_KEYS = ["notification", "chat", "message"]

PARTNER_REQUEST_EXTRA_KEYS = [
    "approval",
    "contract",
    "contract_legal_document",
    "clause",
    "clause_performers_editor",
    "clause_quick_actions",
]

PAGE_KEYS = ["explore"]

FILE_HEADER = "/* Auto-generated by scripts/reorg-locales.py */\n"


@dataclass
class ExtractedBlock:
    key: str
    object_text: str
    start: int
    end: int


def ensure_dir(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)


def find_key_index(source: str, key: str) -> int:
    patterns = [
        rf"\n\s*{re.escape(key)}\s*:\s*\{{",
        rf"\n\s*\"{re.escape(key)}\"\s*:\s*\{{",
        rf"\n\s*\'{re.escape(key)}\'\s*:\s*\{{",
    ]
    for pattern in patterns:
        match = re.search(pattern, source)
        if match:
            return match.start()
    return -1


def extract_object_literal(source: str, key: str) -> ExtractedBlock | None:
    key_index = find_key_index(source, key)
    if key_index == -1:
        return None

    brace_start = source.find("{", key_index)
    if brace_start == -1:
        return None

    i = brace_start
    depth = 0
    in_string: str | None = None
    escape = False
    template_expr_depth = 0

    while i < len(source):
        char = source[i]
        next_char = source[i + 1] if i + 1 < len(source) else ""

        if in_string:
            if escape:
                escape = False
                i += 1
                continue

            if char == "\\":
                escape = True
                i += 1
                continue

            if in_string == "`" and char == "$" and next_char == "{":
                template_expr_depth = 1
                i += 2
                continue

            if template_expr_depth > 0:
                if char == "{":
                    template_expr_depth += 1
                elif char == "}":
                    template_expr_depth -= 1
                i += 1
                continue

            if char == in_string:
                in_string = None
            i += 1
            continue

        if char in ["'", '"', "`"]:
            in_string = char
            i += 1
            continue

        if char == "{":
            depth += 1
        elif char == "}":
            depth -= 1
            if depth == 0:
                object_text = source[brace_start : i + 1]
                line_start = source.rfind("\n", 0, brace_start) + 1
                end = i + 1
                while end < len(source) and source[end] in " \t\r\n,":
                    if source[end] == "\n":
                        end += 1
                        break
                    end += 1
                return ExtractedBlock(key, object_text, line_start, end)
        i += 1

    return None


def build_object_export(entries: list[ExtractedBlock]) -> str:
    body = "\n".join([f"  {entry.key}: {entry.object_text}," for entry in entries])
    return f"{FILE_HEADER}export default {{\n{body}\n}};\n"


def replace_range(source: str, start: int, end: int, replacement: str) -> str:
    return source[:start] + replacement + source[end:]


def remove_ranges(source: str, ranges: list[tuple[int, int]]) -> str:
    for start, end in sorted(ranges, key=lambda item: item[0], reverse=True):
        source = replace_range(source, start, end, "")
    return source


def replace_block(source: str, block: ExtractedBlock, replacement: str) -> str:
    return replace_range(source, block.start, block.end, replacement)


def ensure_import(source: str, import_line: str) -> str:
    if import_line in source:
        return source
    matches = list(re.finditer(r"^import .+$", source, flags=re.MULTILINE))
    if not matches:
        return f"{import_line}\n{source}"
    last = matches[-1]
    insert_pos = last.end()
    return source[:insert_pos] + "\n" + import_line + source[insert_pos:]


def rename_split_bill_folder() -> None:
    src = ZH_DIR / "split_the_bill"
    dest = ZH_DIR / "split_bill"
    if not src.exists() or dest.exists():
        return
    src.rename(dest)


def remove_empty_me_folder() -> None:
    me_dir = ZH_DIR / "me"
    if not me_dir.exists() or not me_dir.is_dir():
        return
    if any(me_dir.iterdir()):
        return
    me_dir.rmdir()


def write_file(path: Path, content: str) -> None:
    path.write_text(content, encoding="utf-8")


def update_zh_hans() -> None:
    source = ZH_MAIN.read_text(encoding="utf-8")

    common_blocks = [
        block
        for key in COMMON_KEYS
        if (block := extract_object_literal(source, key)) is not None
    ]

    communication_blocks = [
        block
        for key in COMMUNICATION_KEYS
        if (block := extract_object_literal(source, key)) is not None
    ]

    partner_extra_blocks = [
        block
        for key in PARTNER_REQUEST_EXTRA_KEYS
        if (block := extract_object_literal(source, key)) is not None
    ]

    explore_block = extract_object_literal(source, "explore")

    if common_blocks:
        write_file(ZH_DIR / "common.ts", build_object_export(common_blocks))

    if communication_blocks:
        write_file(ZH_DIR / "communication.ts", build_object_export(communication_blocks))

    if partner_extra_blocks:
        partner_extra = "\n".join(
            [f"  {entry.key}: {entry.object_text}," for entry in partner_extra_blocks]
        )
        content = (
            f"{FILE_HEADER}import basePartnerRequest from \"./partner_request/index\";\n\n"
            f"export default {{\n  ...basePartnerRequest,\n{partner_extra}\n}};\n"
        )
        write_file(ZH_DIR / "partner_request.ts", content)

    write_file(ZH_DIR / "base.ts", f"{FILE_HEADER}export {{ default }} from \"./base/index\";\n")
    write_file(
        ZH_DIR / "account.ts", f"{FILE_HEADER}export {{ default }} from \"./account/index\";\n"
    )
    write_file(
        ZH_DIR / "onboarding.ts",
        f"{FILE_HEADER}export {{ default }} from \"./onboarding/index\";\n",
    )
    write_file(
        ZH_DIR / "split_bill.ts", f"{FILE_HEADER}export {{ default }} from \"./split_bill/index\";\n"
    )

    page_content = (
        f"{FILE_HEADER}import explore from \"./explore\";\n\n"
        "export default {\n  explore: {\n    ...explore,\n  },\n};\n"
    )
    write_file(ZH_DIR / "page.ts", page_content)

    if common_blocks:
        common_block = next((b for b in common_blocks if b.key == "common"), None)
        if common_block:
            source = replace_block(source, common_block, "  ...common,\n")
        to_remove = [b for b in common_blocks if b.key != "common"]
        source = remove_ranges(source, [(b.start, b.end) for b in to_remove])

    if communication_blocks:
        notification_block = next(
            (b for b in communication_blocks if b.key == "notification"), None
        )
        if notification_block:
            source = replace_block(source, notification_block, "  ...communication,\n")
        to_remove = [b for b in communication_blocks if b.key != "notification"]
        source = remove_ranges(source, [(b.start, b.end) for b in to_remove])

    if explore_block:
        source = replace_block(source, explore_block, "  ...page,\n")

    if partner_extra_blocks:
        source = remove_ranges(source, [(b.start, b.end) for b in partner_extra_blocks])

    source = source.replace("./zh-Hans/split_the_bill", "./zh-Hans/split_bill")

    source = ensure_import(source, 'import common from "./zh-Hans/common";')
    source = ensure_import(source, 'import page from "./zh-Hans/page";')
    source = ensure_import(source, 'import communication from "./zh-Hans/communication";')
    source = ensure_import(source, 'import split_bill from "./zh-Hans/split_bill";')

    ZH_MAIN.write_text(source, encoding="utf-8")


def update_en_us() -> None:
    source = EN_MAIN.read_text(encoding="utf-8")

    common_block = extract_object_literal(source, "common")
    explore_block = extract_object_literal(source, "explore")

    if common_block:
        write_file(EN_DIR / "common.ts", build_object_export([common_block]))

    page_content = (
        f"{FILE_HEADER}import explore from \"./explore\";\n\n"
        "export default {\n  explore: {\n    ...explore,\n  },\n};\n"
    )
    write_file(EN_DIR / "page.ts", page_content)

    write_file(EN_DIR / "base.ts", f"{FILE_HEADER}export default {{}};\n")
    write_file(EN_DIR / "account.ts", f"{FILE_HEADER}export default {{}};\n")
    write_file(EN_DIR / "onboarding.ts", f"{FILE_HEADER}export default {{}};\n")
    write_file(EN_DIR / "partner_request.ts", f"{FILE_HEADER}export default {{}};\n")
    write_file(EN_DIR / "split_bill.ts", f"{FILE_HEADER}export default {{}};\n")
    write_file(EN_DIR / "communication.ts", f"{FILE_HEADER}export default {{}};\n")

    if common_block:
        source = replace_block(source, common_block, "  ...common,\n")

    if explore_block:
        source = replace_block(source, explore_block, "  ...page,\n")

    source = ensure_import(source, 'import common from "./en-US/common";')
    source = ensure_import(source, 'import page from "./en-US/page";')
    source = ensure_import(source, 'import base from "./en-US/base";')
    source = ensure_import(source, 'import account from "./en-US/account";')
    source = ensure_import(source, 'import onboarding from "./en-US/onboarding";')
    source = ensure_import(source, 'import partner_request from "./en-US/partner_request";')
    source = ensure_import(source, 'import split_bill from "./en-US/split_bill";')
    source = ensure_import(source, 'import communication from "./en-US/communication";')

    if "base:" not in source:
        source = source.replace(
            "  ...page,\n",
            "  ...page,\n  base: {\n    ...base,\n  },\n  account: {\n    ...account,\n  },\n"
            "  onboarding: {\n    ...onboarding,\n  },\n  partner_request: {\n    ...partner_request,\n  },\n"
            "  ...split_bill,\n  ...communication,\n",
        )

    EN_MAIN.write_text(source, encoding="utf-8")


def main() -> None:
    ensure_dir(ZH_DIR)
    ensure_dir(EN_DIR)
    rename_split_bill_folder()
    remove_empty_me_folder()
    update_zh_hans()
    update_en_us()


if __name__ == "__main__":
    main()
